export const BOOTHS = [
  'BSI Sponsor 31',
  'BSI Sponsor 32',
  'MIW',
  'MIW ABT',
  'Al Fajr',
  'Hajar Aswad',
  'Firdaus Mulia Abadi',
  'Dewangga',
  'Golden Jannah',
  'Al Bayt',
  'Mubarak Tour',
  'Surya Madina',
  'Baitullah Tiga Kharisma (Batik Tour)',
  'Ghulam Kopor',
  'Jelajah Wisata Thoyibah',
  'Namira Travel Solo',
  'El Ghazali',
  'Marco',
  'Zatabbaru',
  'Nur Ramadhan Solo',
  'NikmaTour',
  'Hilal Tour',
];